### ISSUE TITLE
sass-variables

### ISSUE THREAD

**Issue by kilkujadek** [Hernanm0g/meteor-vuetify-loader#5]
Hello,

Is it possible to use your loader with [sass-variables](https://dev.vuetifyjs.com/en/api/vuetify/#sass-variables)? Would you be able to prepare some example?

**Comment by Hernanm0g** [comment]
HI @kilkujadek . Im going to check this and give you an answer as soon as i can

**Comment by Hernanm0g** [comment]
## SASS Variables
In order to use the custom [sass-variables](https://vuetifyjs.com/en/features/sass-variables), do this:
1. Create a file named user_variables.scss, anywhere inside imports/ folder. for instance: `/imports/ui/styles/vuetify/user_variables.scss`
2. Put your variables definitions inside user_variables.scss:
    ```less
    $btn-sizes: (
      'default': 60,
      'large': 90
    );
    ```
3. Create a file named `scss-config.json` as a direct child of your main app folder.
4. Create an array inside the prop includePaths, and place there the **PATH** (without the file name!!) of the folder where user_variables.scss is. 
    ```json
    {
      "includePaths": [
        "{}/imports/ui/styles/vuetify/"
      ]
    }
    ```
Thats it!
